name: Check and test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version:
          - "3.8" # minimum required
          - "3.12" # latest
          - "3.13-dev" # next

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.python-version == '3.13-dev' }}

    steps:
      - run: sudo apt-get install flac mp3val oggz-tools
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - run: poetry env use $(which python)
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run isort --check .
      - run: poetry run flake8
      - run: poetry run pytest

  build-beets-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        beets:
          - "git+https://github.com/beetbox/beets#master"
          - "beets==1.6.1"

    steps:
      - run: sudo apt-get install flac mp3val oggz-tools
      - uses: actions/checkout@v4
      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: poetry
      - run: poetry env use $(which python)
      - run: poetry install
      - run: poetry add ${{ matrix.beets }}
      - run: poetry run pytest
