name: Check and test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version:
          - "3.8" # minimum required
          - "3.12" # latest
          - "3.13-dev" # next

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.python-version == '3.13-dev' }}

    steps:
      - run: sudo apt-get install flac mp3val oggz-tools
      - uses: actions/checkout@v3
      - run: pip install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - run: poetry env use $(which python)
      - run: poetry install
      - run: poetry run flake8
      - run: poetry run pytest

  build-beets-master:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - run: sudo apt-get install flac mp3val oggz-tools
      - uses: actions/checkout@v3
      - run: pip install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: poetry
      - run: poetry env use $(which python)
      - run: poetry install
      # We cannot use `poetry add` because poetry does not install beets
      # dependencies properly
      - run: poetry run pip install "git+https://github.com/beetbox/beets#master"
      - run: poetry run pytest
