name: Check and test

on: [push, pull_request]

env:
  FORCE_COLOR: "1"

jobs:
  build:
    strategy:
      matrix:
        python-version:
          - "3.10" # minimum required
          - "3.13"
          - "3.14"

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.python-version == '3.14' }}

    steps:
      - run: sudo apt-get install flac mp3val oggz-tools
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "UV_PYTHON=${{ steps.setup-python.outputs.python-path }}" >> "$GITHUB_ENV"
      - run: uv lock --locked
      - run: uv sync --all-extras --dev
      - run: uv run ruff check .
      - run: uv run pytest

  build-beets-versions:
    strategy:
      matrix:
        beets:
          - "beets@git+https://github.com/beetbox/beets#master"
          - "beets==2.0.*"
          - "beets==2.1.*"

    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.beets, 'master') }}

    steps:
      - run: sudo apt-get install flac mp3val oggz-tools
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: 3.13
      - run: echo "UV_PYTHON=${{ steps.setup-python.outputs.python-path }}" >> "$GITHUB_ENV"
      - run: uv lock -P ${{ matrix.beets }}
      - run: uv sync --all-extras --dev
      - run: uv run pytest
